[build]
functions = "src"

[functions]
included_files = ["clientside/**"]

[[redirects]]
from = "/proxy/*"
to = "/.netlify/functions/index"
status = 200

[[redirects]]
from = "/go"
to = "/.netlify/functions/index"
status = 200
